---
- hosts: all
  name: Install Terraform and related utilities
  roles:
    - go
    - stow
  tasks:
    - name: Create XDG directory
      file:
        path: "{{ stow }}/terraform-{{ terraform_version }}/bin"
        state: directory
    - name: Download TF
      unarchive:
        remote_src: yes
        src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "{{ stow }}/terraform-{{ terraform_version }}/bin"
        creates: "{{ stow }}/terraform-{{ terraform_version }}/bin/terraform"
    - name: Get installed version
      shell: terraform -version | head -n 1 | grep -P -o -e "\d+\.\d+\.\d+" -
      register: installed_version
    - name: Stow TF
      command: stow -D terraform-{{ installed_version.stdout }} -S terraform-{{ terraform_version }}
    - name: Alias Terraform
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bash_aliases"
        line: "alias tf=terraform"
    - name: Install terraform-docs
      command: go get -u github.com/segmentio/terraform-docs
    - name: Alias terraform-docs
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bash_aliases"
        line: "alias tf-docs=terraform-docs"
    - name: Install scenery
      command: go get -u github.com/dmlittle/scenery
