---
- include_role:
    name: apt
- name: Install systemd container tools
  apt: name=systemd-container state=present
- name: Installed packages
  package_facts:
    manager: apt
- name: Install rkt
  apt:
    deb="https://github.com/rkt/rkt/releases/download/v{{ rkt_version }}/rkt_{{ rkt_version }}-1_amd64.deb"
  become: true
  become_method: sudo
  when: '"rkt" in ansible_facts.packages and ansible_facts.packages.rkt[0]["version"] != "{{ rkt_version }}-1"'
