---
build_dir: "{{ ansible_env.HOME }}/boxsible_build"
install_dir: /opt
home: "{{ ansible_env.HOME }}"
src: "{{ home }}/.local/src"
stow: "{{ home }}/.local/stow"

chruby_version: 0.3.9
go_version: 1.11.5
profanity_version: 0.5.1
python_version: 3.7.2
rkt_version: 1.30.0
ruby_install_version: 0.6.1
terraform_version: 0.11.11
vte_version: 0.54.2.a
