---
- name: Create XDG directory structure
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ home }}/.config"
    - "{{ home }}/.cache"
    - "{{ home }}/.local/bin"
    - "{{ home }}/.local/lib"
    - "{{ home }}/.local/share"
    - "{{ home }}/.local/src"
- name: Add lib path
  lineinfile:
    path: "{{ home }}/.bash_profile"
    line: "LD_LIBRARY_PATH={{ home }}/.local/lib:$LD_LIBRARY_PATH"
    state: present
