---
- name: Set current go version
  shell: go version | cut -f 3 -d ' ' | cut -b 3-
  register: go
  ignore_errors: True
- name: Remove old Go version
  file:
    state: absent
    path: "/usr/local/go/"
  become: true
  become_method: sudo
  when: go.stdout != go_version
- name: Download Go
  unarchive:
    remote_src: yes
    src: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    creates: /usr/local/go/bin/go
  become: true
  become_method: sudo
- name: Add Go to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: 'PATH=/usr/local/go/bin:$PATH'
    state: present
