---
- include_role:
    name: apt
- name: Install apt packages
  apt: name={{ item }} state=installed
  with_items:
    - automake
    - autoconf
    - autoconf-archive
    - libtool
    - pkg-config
  become: true
  become_method: sudo
- name: Make build directory
  file:
    path: "{{ build_dir }}"
    state: directory
